"use strict";
/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is located at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.isRetryableException = exports.isBadRequestException = exports.isResourcePreconditionNotMetException = exports.isResourceNotFoundException = exports.isOccConflictException = exports.isTransactionExpiredException = exports.isInvalidSessionException = exports.isInvalidParameterException = exports.ExecuteError = exports.SessionPoolEmptyError = exports.LambdaAbortedError = exports.DriverClosedError = exports.ClientError = void 0;
const LogUtil_1 = require("../LogUtil");
const transactionExpiredPattern = RegExp("Transaction .* has expired");
class ClientError extends Error {
    /**
     * @internal
     */
    constructor(message) {
        super(message);
        Object.setPrototypeOf(this, ClientError.prototype);
        this.message = message;
        this.name = "ClientError";
        LogUtil_1.error(message);
    }
}
exports.ClientError = ClientError;
class DriverClosedError extends Error {
    /**
     * @internal
     */
    constructor() {
        const message = "Cannot invoke methods on a closed driver. Please create a new driver and retry.";
        super(message);
        Object.setPrototypeOf(this, DriverClosedError.prototype);
        this.message = message;
        this.name = "DriverClosedError";
        LogUtil_1.error(message);
    }
}
exports.DriverClosedError = DriverClosedError;
class LambdaAbortedError extends Error {
    /**
     * @internal
     */
    constructor() {
        const message = "Abort called. Halting execution of lambda function.";
        super(message);
        Object.setPrototypeOf(this, LambdaAbortedError.prototype);
        this.message = message;
        this.name = "LambdaAbortedError";
        LogUtil_1.error(message);
    }
}
exports.LambdaAbortedError = LambdaAbortedError;
class SessionPoolEmptyError extends Error {
    /**
     * @internal
     */
    constructor() {
        const message = "Session pool is empty. Please close existing sessions first before retrying.";
        super(message);
        Object.setPrototypeOf(this, SessionPoolEmptyError.prototype);
        this.message = message;
        this.name = "SessionPoolEmptyError";
        LogUtil_1.error(message);
    }
}
exports.SessionPoolEmptyError = SessionPoolEmptyError;
/**
 * @internal
 */
class ExecuteError extends Error {
    constructor(cause, isRetryable, isInvalidSessionException, transactionId = null) {
        const message = "Error containing the context of a failure during Execute.";
        super(message);
        Object.setPrototypeOf(this, ExecuteError.prototype);
        this.cause = cause;
        this.isRetryable = isRetryable;
        this.isInvalidSessionException = isInvalidSessionException;
        this.transactionId = transactionId;
    }
}
exports.ExecuteError = ExecuteError;
/**
 * Is the exception an InvalidParameterException?
 * @param e The client error caught.
 * @returns True if the exception is an InvalidParameterException. False otherwise.
 */
function isInvalidParameterException(e) {
    return e.code === "InvalidParameterException";
}
exports.isInvalidParameterException = isInvalidParameterException;
/**
 * Is the exception an InvalidSessionException?
 * @param e The client error caught.
 * @returns True if the exception is an InvalidSessionException. False otherwise.
 */
function isInvalidSessionException(e) {
    return e.code === "InvalidSessionException";
}
exports.isInvalidSessionException = isInvalidSessionException;
/**
 * Is the exception because the transaction expired? The transaction expiry is a message wrapped
 * inside InvalidSessionException.
 * @param e The client error to check to see if it is an InvalidSessionException due to transaction expiry.
 * @returns Whether or not the exception is is an InvalidSessionException due to transaction expiry.
 */
function isTransactionExpiredException(e) {
    return e.code === "InvalidSessionException" && transactionExpiredPattern.test(e.message);
}
exports.isTransactionExpiredException = isTransactionExpiredException;
/**
 * Is the exception an OccConflictException?
 * @param e The client error caught.
 * @returns True if the exception is an OccConflictException. False otherwise.
 */
function isOccConflictException(e) {
    return e.code === "OccConflictException";
}
exports.isOccConflictException = isOccConflictException;
/**
 * Is the exception a ResourceNotFoundException?
 * @param e The client error to check to see if it is a ResourceNotFoundException.
 * @returns Whether or not the exception is a ResourceNotFoundException.
 */
function isResourceNotFoundException(e) {
    return e.code === "ResourceNotFoundException";
}
exports.isResourceNotFoundException = isResourceNotFoundException;
/**
 * Is the exception a ResourcePreconditionNotMetException?
 * @param e The client error to check to see if it is a ResourcePreconditionNotMetException.
 * @returns Whether or not the exception is a ResourcePreconditionNotMetException.
 */
function isResourcePreconditionNotMetException(e) {
    return e.code === "ResourcePreconditionNotMetException";
}
exports.isResourcePreconditionNotMetException = isResourcePreconditionNotMetException;
/**
 * Is the exception a BadRequestException?
 * @param e The client error to check to see if it is a BadRequestException.
 * @returns Whether or not the exception is a BadRequestException.
 */
function isBadRequestException(e) {
    return e.code === "BadRequestException";
}
exports.isBadRequestException = isBadRequestException;
/**
 * Is the exception a retryable exception?
 * @param e The client error caught.
 * @returns True if the exception is a retryable exception. False otherwise.
 *
 * @internal
 */
function isRetryableException(e) {
    return isRetryableStatusCode(e) || isOccConflictException(e) ||
        (isInvalidSessionException(e) && !isTransactionExpiredException(e));
}
exports.isRetryableException = isRetryableException;
/**
 * Does the error have a retryable code or status code?
 * @param e The client error caught.
 * @returns True if the exception has a retryable code.
 */
function isRetryableStatusCode(e) {
    return (e.statusCode === 500) ||
        (e.statusCode === 503) ||
        (e.code === "NoHttpResponseException") ||
        (e.code === "SocketTimeoutException");
}
